### PR TITLE
Pagination index update

### PR DESCRIPTION
**Pull request by beekus**
Add pagination docs for configuration versions.

### CODE REVIEW

**Comment by beekus** [comment]
associated TFE pr: https://github.com/hashicorp/atlas/pull/6238

**Comment by nfagerlund** [comment]
#294 has this as well, but doesn't update the index. QUESTION: Do we actually want to keep adding these pages to the index? I say no, because the admin pages API is gonna add like another five paginated endpoints iirc, so we should probably say something like "Most of the endpoints that return lists of objects support pagination."

**Comment by beekus** [comment]
oh ha. woops. it was too early in the morning and i didn't see ryan's PR

**Comment by beekus** [comment]
probably a good point. yeah, we can change the text there.

**Pull request merged**
