### PR TITLE
Update open graph image

### PR DESCRIPTION
**Pull request by lunchbag**
The design and marketing team worked together on a new set of assets to be used when sharing to Twitter/Facebook (aka `og:image`). This PR contains the update for the Terraform image.

### CODE REVIEW

**Comment by phinze** [comment]
See #214 and #237 and #242 for reference in my Quest for Reasonable Slack Unfurls ⚔️🐉

**Comment by lunchbag** [comment]
Hey @phinze, it definitely sounds like this was a pain point for you! Do you happen to have any screenshots of what this looked like or what you're trying to avoid? I wonder if it was like this:

screenshot 2018-11-14 17 46 15

I went ahead and added another change which is to use `summary_large_image` which should unfurl the image into a large image rather than a smaller image at the top right. And since this new image is not a square but a horizontal rectangle, it shouldn't look awkwardly boxy and out of place. Maybe this will help solve the issue you mentioned. You can see the difference it makes in this PR comment: https://github.com/hashicorp/hashicorp-www-middleman/pull/1261

I tried to get `terraform-website` to build off Netlify such that we could test this, but ran into issues.  Do you have another method? If not, we can wait for Vagrant and Packer (both of which who have approved and merged this change) to update their website and you can see what the new images look like. All the new sets of images are the same res and dimensions. Alternatively, it's also live on https://learn.hashicorp.com. Here's how https://learn.hashicorp.com/terraform looks in Slack:

screenshot 2018-11-14 17 47 37

**Comment by lunchbag** [comment]
Hi @phinze, let me know if there's anything else you would like me to verify in order to get this merged. Thanks :D

**Comment by phinze** [comment]
Hi @lunchbag sorry for the delay! Yep that Vagrant example is exactly the "too tall unfurl" that I was talking about.

Here's a "reasonable height unfurl" example:

2018-11-20 at 11 13 am

I'm okay to get out of the way so you can test this by deploying (pending @nfagerlund's OK) and seeing how tall the unfurls come out. I'll remove my ❌ so you are unblocked.

**Comment by lunchbag** [comment]
@phinze Thanks! FYI, https://vaultproject.io's new images are up, so you can test it out if there are similar subpages, like https://www.vaultproject.io/docs/secrets/alicloud/index.html

**Comment by nfagerlund** [comment]
@lunchbag Do you have merge permissions on this repo, or should I push the button for you? (And would you rather I not merge it on Thanksgiving's Eve's Eve?)

**Comment by phinze** [comment]
2018-11-20 at 4 32 pm

Hm the vault site unfurls are pretty darn big. I'll keep my fingers crossed that this doesn't come out so tall! The idea here is that docs links unfurling so big really breaks up conversation involving docs that you are trying to discuss.

The right-aligned "T" logo worked way better for that use case and was a significant daily life improvement when it landed that we got a lot of positive feedback on. Let's see how this goes but if the Terraform unfurls come out like the Vault ones do I think I'll be pulling for us to keep the "T".

**Comment by lunchbag** [comment]
@phinze It will be the same as what you see for Vault. The idea is to have images consistent across all sites. You bring up a valid point regarding large interruptive unfurls in conversations on Slack. Let me chat with the designer/developer who worked on these new assets and get back to you on this. No rush on getting this out just yet @nfagerlund, but definitely want to make sure whatever we put out there is something everyone will be happy with!

**Comment by lunchbag** [comment]
Sorry for the super late follow up, but @phinze would you want the smaller image to be for every single page, or just the docs pages?

**Comment by phinze** [comment]
@lunchbag I think it's most important for any page that would be linked into Slack as a references, so docs and guides and such. I think it'd be fine to have the same smaller image for all pages, but I feel less strongly about non-docs pages so I'll leave that up to you.

**Comment by lunchbag** [comment]
@phinze Great, glad we finally got to a solution :) Sorry that it got dragged out a bit!

**Comment by nfagerlund** [comment]
superseded by #677

**Pull request closed without merging**
