### PR TITLE
.circleci: Initial attempt at building and pushing multi-architecture images

### LINKED ISSUE #2378: Consider Building Multi-Architecture Docker Images (Native arm64 Support)
## Description

When running the `make website` target in any of the /plugin remote content repositories, e.g. /plugin/mux's terraform-plugin-mux, the local website compilation is quite slow with an Apple M1 machine.

Full startup logs and some browsing from root to /plugin/mux:

<details>
make website
==> Downloading latest Docker image...
full: Pulling from hashicorp/terraform-website
ddad3d7c1e96: Pull complete
f845e0f7d73a: Pull complete
47d471c4d820: Pull complete
1a88008f9c83: Pull complete
16ea9a77baaf: Pull complete
c157a7493495: Pull complete
325000b8dc2a: Pull complete
3b4474878c0a: Pull complete
bfb1afa41ad6: Pull complete
Digest: sha256:81a4750ee7040adc8690a8c66c24fe81706d77c8568ca3d87ef98bff9b856966
Status: Downloaded newer image for hashicorp/terraform-website:full
docker.io/hashicorp/terraform-website:full
==> Starting website in Docker...
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

> terraform-website@1.0.0 start
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /website/.env
info  - automatically enabled Fast Refresh for 1 custom loader
event - compiled client and server successfully in 27.9s (548 modules)
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

wait  - compiling / (client and server)...
event - compiled client and server successfully in 12.9s (1022 modules)
[bugsnag] Loaded!
wait  - compiling /plugin/[[...page]]...
event - compiled client and server successfully in 10.7s (1324 modules)
wait  - compiling /plugin/[[...page]] (client and server)...
event - compiled client and server successfully in 10.9s (1586 modules)
[bugsnag] Loaded!
wait  - compiling /plugin/log/[[...page]]...
event - compiled client and server successfully in 2.3s (1327 modules)
wait  - compiling /plugin/log/[[...page]] (client and server)...
event - compiled client and server successfully in 955 ms (1589 modules)
</details>

It seems to be related to the following warning in the above logs on container startup:

```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Because as soon as I switch to `make website/build-local`, which would build the terraform-website image matching my machine's architecture, and `make website/local`, everything is quite speedy.

<details>
make website/local
==> Starting website in Docker...

> terraform-website@1.0.0 start
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /website/.env
info  - automatically enabled Fast Refresh for 1 custom loader
event - compiled client and server successfully in 2.8s (548 modules)
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

wait  - compiling /404 (client and server)...
event - compiled client and server successfully in 79 ms (549 modules)
[bugsnag] Loaded!
wait  - compiling / (client and server)...
event - compiled client and server successfully in 1192 ms (1023 modules)
wait  - compiling /plugin/[[...page]] (client and server)...
event - compiled client and server successfully in 1881 ms (1649 modules)
[bugsnag] Loaded!
wait  - compiling /plugin/mux/[[...page]] (client and server)...
event - compiled client and server successfully in 262 ms (1654 modules)
</details>

I'm guessing either Docker or Rosetta is handling the automatic CPU translation when running the other image causing the performance issue.

## Proposal

In addition to amd64 architecture `hashicorp/terraform-website:full` images, publish arm64 architecture images. Anything needing arm64 should automatically pull the correct architecture and get the performance improvement.

## References

- https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/
- https://docs.docker.com/desktop/multi-arch/

### PR DESCRIPTION
**Pull request by bflad**
### What

Setup the CircleCI website-docker-image job to build and push images for both amd64 and arm64.

I'm not exactly sure if you folks have the ability to test this job update before trying it out, as I'm more used to GitHub Actions `docker/setup-buildx-action` to handle the buildx bits and `act` for local testing. If you'd like to migrate this to GitHub Actions, happy to assist that effort (I just cannot help with the secrets side of things, but I can help coordinate with the folks who can).

### Why

Performance on arm64 architecture machines, e.g. Apple M chips.

Closes #2378
Reference: https://circleci.com/docs/building-docker-images
Reference: https://docs.docker.com/engine/reference/commandline/buildx_build

### Screenshots

----------

### Merge Checklist
_If items do not apply to your changes, add (N/A) and mark them as complete._

#### Pull Request
- [ ] One or more labels describe the type of change (e.g. clarification) and associated product (e.g. tfc).
- [ ] Description links to related pull requests or issues, if any.

#### Content
- [ ] Redirects have been added for moved, renamed, or deleted pages.
- [ ] Sidebar navigation files have been updated for added, deleted, reordered, or renamed pages.
- [ ] Links to related content where appropriate (e.g., API endpoints, permissions, etc.).
- [ ] Pages with related content are updated and link to this content when appropriate.
- [ ] New pages have metadata (page name and description) at the top.
- [ ] New images are 2048 px wide. They have HashiCorp standard annotation color (#F92672) and format (rectangle with rounded corners), blurred sensitive details (e.g. credentials, usernames, user icons), and descriptive alt text in the markdown for accessibility.
- [ ] New code blocks have the correct syntax and line breaks to eliminate horizontal scroll bars.
- [ ] UI elements (button names, page names, etc.) are bolded.
- [ ] The Vercel website preview successfully deployed.

#### Reviews
- [ ] I or someone else reviewed the content for technical accuracy.
- [ ] I or someone else reviewed the content for typos, punctuation, spelling, and grammar.

### CODE REVIEW

**Comment by dstaley** [comment]
@thiskevinwang tagging you for review since you did the multi-arch builds for dev portal

**Review by thiskevinwang — APPROVED** [review]
@bflad this LGTM, though I'm not actually sure how to test this aside from letting the job run in CircleCI

As a sidenote: It's worth mentioning that this website repository is going to be deprecated soon, and the `make` commands that the various Terraform properties use will eventually use an image that is built from https://github.com/hashicorp/dev-portal (which is already [multi-arch](https://github.com/hashicorp/dev-portal/blob/main/.github/workflows/docker_publish.yml#L60))

**Comment by bflad** [comment]
@thiskevinwang 😍 that's awesome news. I guess maybe the best thing to do here probably depends on how long that'll be. If it is like, soon, then maybe best to just leave this as-is. Otherwise, maybe we should queue a small or non-consequential change right behind this so we can immediately test and fix/revert this if necessary?

**Comment by bflad** [comment]
If anything needs to be done, it'll be in the devdot platform now.

**Pull request closed without merging**
