### PR TITLE
Added AppRole token_max_ttl

### PR DESCRIPTION
**Pull request by justinretzolk**
Addresses issue of token expiring before Terraform Enterprise can request a new one.

### CODE REVIEW

**Comment by glasner** [comment]
### Do not merge
Until @nfagerlund is done with the great recategorization

**Comment by evanphx** [comment]
This is good though I don't think it addresses the maximum renewal issue.

**Comment by justinretzolk** [comment]
@nfagerlund: I noticed that the Travis CI builds failed on this so wanted to double check with you again before merging. If I can safely ignore it in this case, I'll get it merged.

**Comment by nfagerlund** [comment]
@justinretzolk Travis can be ignored in this case! It was being flaky yesterday for unrelated reasons, and the broken links are already on my radar and not part of this PR. 

I'll go ahead and merge it, since I'm in here!

**Pull request merged**
