### PR TITLE
Clarify scope of tokens, especially re: private modules

### PR DESCRIPTION
**Pull request by nfagerlund**
After talking with Ryan, I decided to NOT raise the possibility of overwriting ATLAS_TOKEN in the context of private modules.

### CODE REVIEW

**Comment by rberlind** [comment]
The docs seem ok, but the only reference to using a module from a different organization is:

"When you authenticate with a user token, you can access modules from any organization you are a member of. (A user is a member of an organization if they belong to any team in that organization.)"

I feel that we could say more here such as: "If you reference a module in one organization from a workspace in a second organization, this will work as long as you are a member of both organizations."

**Comment by nfagerlund** [comment]
@rberlind But it _won't_ work when TFE is doing the run, right? Unless you overwrite ATLAS_TOKEN, which we're discouraging for this purpose.

**Comment by skierkowski** [comment]
you are right, it will NOT work if you are running it in TFE, but it will work if running locally. In other words, when running locally you are probably using your personal ATLAS_TOKEN, and when running TFE you are probably using the auto-generated token.

My general feedback is this:
- We must document if personal ATLAS_TOKENS and auto generated tokens have cross-org access.
- We should discourage the use of a personal ATLAS_TOKEN in a workspace, either by not documenting or explicitly calling out that it is discouraged.
- We may document the use of the use of personal ATLAS_TOKEN in a workspace, but only as an exception and specific to use cases (e.g. manually migration), other than that, it shouldn't be called out.
- If there are some exceptions, support team may reference these docs on access levels to explain the access levels, but the use of the personal ATLAS_TOKEN should be called out in 1-1 communications with a customer.

As a side note, the one use case for the private module registry and cross-org access came from a customer who has since then found an alternative design which no longer requires this.

**Comment by rberlind** [comment]
Apologies, @nfagerlund.  I was confused because runs in TFE UI against module in different org used to work in older version, but then we tightened security to require ATLAS_TOKEN as Maciej described. I had forgotten about that change.

**Comment by nfagerlund** [comment]
Cool cool. In that case, shall I go ahead and merge?

**Comment by rberlind** [comment]
I have no objection to merge.

**Comment by skierkowski** [comment]
> I think this PR stays within your guidelines by not mentioning personal tokens as an option;

@nfagerlund 👍 for me

**Pull request merged**
