### PR TITLE
Remove Atlas and legacy migration docs

### PR DESCRIPTION
**Pull request by alisdair**
The Atlas migration functionality has been removed for some time now, so these docs should no longer be needed.

- Remove out of date migration API docs
- Remove Terraform Enterprise v1 (Atlas) docs
- Remove references to the above deleted docs
- Fix some old API responses (ingress-trigger-attributes is no more)

### CODE REVIEW

**Comment by alisdair** [comment]
Not yet…

**Comment by alisdair** [comment]
Maybe this is okay after all? @rkst approves the idea at least.

**Comment by alisdair** [comment]
[Here's a PR for Terraform](https://github.com/hashicorp/terraform/pull/21648) removing links to now-removed docs.

There's also [a broken link from terraform-provider-atlas](https://github.com/terraform-providers/terraform-provider-atlas/blob/9345fd78e9e0d177b7c121505bbebdfff7dec1d3/website/docs/index.html.markdown), but the repository is archived so I don't know what to do about that. Tests are failing. I tried adding a redirect in a71ca65 but it didn't seem to work.

@nfagerlund, any advice?

**Comment by alisdair** [comment]
8c46ece attempts to remove the atlas provider submodule altogether, which seems like a reasonable idea at this point. We'll see if it helps with the test failure, at least…

**Comment by nfagerlund** [comment]
Hmm, I think that'll probably put the build green. Let's see. 

If it goes green I'm pulling the trigger, btw.

**Comment by alisdair** [comment]
Thank you! 😍

**Pull request merged**
