### PR TITLE
Add Alert Banner click track event w/ necessary features to test variant text

### PR DESCRIPTION
**Pull request by JMFURY**
This PR adds an additional track event to the `.notification` Alert Banner-style elements

### CODE REVIEW

**Comment by JMFURY** [comment]
Thanks for the review @nfagerlund ! Much appreciated!

**Comment by JMFURY** [comment]
@nfagerlund  - I rebased on `master` now that it was working for the build. Looks to be okay now. 

Let me know of anything else I should be aware of.

**Comment by nfagerlund** [comment]
@JMFURY Would you like me to go ahead and merge it? Wasn't sure if you wanted it live yet.

**Comment by JMFURY** [comment]
Ah! Sorry about that. 

Yes it's good to go! Thanks so much!

**Pull request merged**
