### PR TITLE
docs: add dlv flags in debugging

### PR DESCRIPTION
**Pull request by remyleone**
add continue and accept-multiclient to dlv command

The specified command was not working for me

## Labels

- [x] inaccuracy
- [x] clarification
- [x] new docs

### CODE REVIEW

**Comment by paddycarver** [comment]
Can you expand on what "not working for me" means?

**Comment by remyleone** [comment]
I was not able to connect from my IDE (goland) to the binary running in debug mode.

**Comment by paddycarver** [comment]
Did it give you any errors?

**Comment by laurapacilio** [comment]
Hi all - just poking this to see if we can get it resolved :-) @remyleone did you have any additional comments here?

**Comment by remyleone** [comment]
When I was trying the command without the options I added, the debugging process just crashed. I've looked around on the internet and adding the following options made it work on my setup.

**Comment by paddycarver** [comment]
I'd love to see crash output if this is reproducible.

**Comment by laurapacilio** [comment]
@remyleone Thank you for submitting this! Do you have crash output? I think we just want to make _sure_ that this is something that should be documented for everyone in the official docs. I also think it'd be great for us to understand what happened so that we can document further and/or make fixes. 

Let us know, thank you!

**Comment by laurapacilio** [comment]
Hi @remyleone We appreciate your submission! I think in the absence of crash output to clarify, I suggest that we close this PR and perhaps you could submit an issue instead that we could dig into on the backend? Let us know what you think about this, thank you!

**Pull request closed without merging**
