### PR TITLE
Clarify some information about paginating the List Organizations endpoint

### PR DESCRIPTION
**Pull request by nfagerlund**
Once upon a time we went through a paginate-and-deprecate process for all the
list endpoints, but we never really finished the process for orgs, so an
unqualified request will still give you the full list.

1. That's bad and we want to change it soon, so therefore we should let people
know they shouldn't rely on it. Stay tuned.

2. The "if omitted" bit in the params table was a little unclear. The pagination
defaults only kick in if you provide at least ONE pagination query param; if you
omit both, you get the whole enchilada.

### CODE REVIEW

**Comment by laurapacilio** [comment]
My only thought on this is - we typically shy away from future-facing statements like the one we are making here. Is it certain that we will make these changes? I think if it's absolutely certain, it's okay and it's good to warn folks. I just always get nervous when talking about what we're going to do, as plans can change :)

**Comment by laurapacilio** [comment]
@nfagerlund are you still working on this? I didn't want to overstep if you weren't ready, but if you are I can review/approve so we can get this merged!

**Comment by nfagerlund** [comment]
@laurapacilio whoop, sorry for missing the notif! You're right, so I adjusted this to avoid a reference to the ✨ the future ✨.

**Review by laurapacilio — APPROVED** [review]
Thank you!  Ship it! 🚀

**Pull request merged**
