### PR TITLE
Replace ; with . for all Query Parameters blocks

### PR DESCRIPTION
**Pull request by anamahalo**
- Admin + missed ones in search/find en masse
    - Follows up on a previous review suggestion
        https://github.com/hashicorp/terraform-website/pull/1875#discussion_r712522840
      - Since changes were preivously one-off prior
        new items going in remained with what was
        already across.  To respect style suggestions
        going back and making changes, but now across
        all areas so consistency remains intact.

Follow-up to https://github.com/hashicorp/terraform-website/pull/1974 happen to see some were missed in the mass search/find, but also admin was missed based on my original search so making sure all are included here.

## Labels

Just marking API since it affects API documentation but no changes.

- [ ] inaccuracy
- [ ] clarification
- [ ] new docs
- [ ] cosmetic bug - fixing broken text or markup
- [ ] enhancement - changing the website's behavior/layout
- [x] api - requires an update to the [changelog](https://www.terraform.io/docs/cloud/api/changelog.html)

### CODE REVIEW

**Review by laurapacilio — APPROVED** [review]

**Comment by anamahalo** [comment]
It looks like that failing GitLab link isn't related but guessing it's failing b/c the `/ce/` actually redirects to `/ee/`.  Will correct and see abouts CI.  :)

**Comment by anamahalo** [comment]
Seems that didn't make a difference though fixing that redirect cleaned up CI a bit but the link that's there on the website works so seems it's a false negative.

**Comment by anamahalo** [comment]
Just confirming here master is green so definitely a false negative.

**Comment by laurapacilio** [comment]
Thank you so much for following up on that :-)

**Pull request merged**
