### PR TITLE
plugin: Add terraform-provider-scaffolding and terraform-provider-scaffolding-framework CTAs

### PR DESCRIPTION
**Pull request by bflad**
Closes hashicorp/terraform-provider-scaffolding-framework#4

This should help increase visibility of this template repository, which can be very helpful for developers to bootstrap a new provider.

### CODE REVIEW

**Review by laurapacilio — COMMENTED** [review]
I like it!! I wonder - are there other places we could add this if it's very helpful? 
I think maybe here: https://www.terraform.io/plugin/framework

**Comment by bflad** [comment]
This change is already for /plugin/framework 😄  if there are other places you think it might be useful, happy to add the links!

**Comment by laurapacilio** [comment]
Haha - forgive me! I was looking at the "Index" part of the file path and I confused /plugin/framework with this page that also has a "get started" section where maybe this would be helpful: https://www.terraform.io/plugin. Essentially, let's add it to both of them!

**Review by paddycarver — APPROVED** [review]

**Comment by bflad** [comment]
Updated the 3 SDK index pages to each have template repository call to actions. 👍

**Review by laurapacilio — APPROVED** [review]
yay! thank you for adding it all the places!

**Pull request merged**
