### PR TITLE
remove cloud/free from io, and redirect to learn

### PR DESCRIPTION
**Pull request by im2nguyen**
## Description
https://app.asana.com/0/1128567758154570/1138535209911322

This is the one at /docs/cloud/free, which isn't reachable from the sidebar. It was a stopgap for the long-finished beta. 

Redirect to learn.

## Notes

 Remove "Getting Started with Free Tier" 

Per Nick's suggestion:

- do a PR that:
   - deletes all the relevant files,
   - adds commented-out mock redirects to that same section of redirects.txt,
   - updates any links throughout the docs to the new locations.
- we all review that PR and agree the plan looks good.
- We go to Alvin and ask for help with the real redirects.
- he deals with it and gives us the 
- we merge

### CODE REVIEW

**Comment by judithpatudith** [comment]
Were there no other links elsewhere in the docs to these pages?

**Comment by im2nguyen** [comment]
> Were there no other links elsewhere in the docs to these pages?

@judithpatudith I don't believe so. before this, there was already redirects from 

```
/docs/enterprise/free                                               /docs/cloud/free
/docs/enterprise/free/                                              /docs/cloud/free/
/docs/enterprise/free/index.html                                    /docs/cloud/free/index.html
/docs/enterprise/free/overview.html                                 /docs/cloud/free/overview.html
```

there's a reference to `/docs/enterprise/free/overview.html` in `content/source/layout/free.erb` (sidebar), but this isn't visible in the sidebar either

the only reference I didn't remove was `/docs/cloud/free/index.html` in `content/scripts/testdata/incoming-links.txt` but will defer to @nfagerlund for that

**Comment by nfagerlund** [comment]
Was reminded of this today! Release engineering will help with the redirects tomorrow, then we can merge this.

**Comment by im2nguyen** [comment]
Hey @nfagerlund, do we have an update on this?

**Comment by nfagerlund** [comment]
Ah, thanks for the ping -- looking into it.

**Comment by nfagerlund** [comment]
The redirects are IN, we can merge this!!!

**Pull request merged**
