### PR TITLE
active/active support bundle addition

### PR DESCRIPTION
**Pull request by mikegreen**
## Labels

- [ ] inaccuracy
- [ x] clarification
- [ ] new docs
- [ ] cosmetic bug - fixing broken text or markup
- [ ] enhancement - changing the website's behavior/layout

### CODE REVIEW

**Comment by mikegreen** [comment]
build fail due to this - 
  - Broken link: https://support.hashicorp.com
    [301 Moved Permanently] https://support.hashicorp.com

which is acceptable

**Review by practicalint — COMMENTED** [review]
Looks good as far as information communicated. The sentence is kinda long. May want to break it up something like multiple sentences and putting the command separate and maybe even in a code box.

**Review by practicalint — CHANGES_REQUESTED** [review]
-> **Note**: For [Terraform Enterprise Active/Active](https://www.terraform.io/docs/enterprise/install/active-active.html) implementations the installer dashboard is disabled. Support bundles can instead be generated and saved to the configured object storage location by executing this command from the command line on a node instance:
 
```
tfe-admin support-bundle
```
This can and should be done individually for every node in the cluster.

**Review by practicalint — APPROVED** [review]
LGTM

**Review by sudomateo — COMMENTED** [review]
Thank you for submitting this!

**Pull request merged**
