### PR TITLE
Minor edits: a stray beta and updated permissions

### PR DESCRIPTION
**Pull request by nfagerlund**
Variable permissions were changed in atlas PR 5573.

### CODE REVIEW

**Comment by nfagerlund** [comment]
Thank you!

I added one commit to remove the word "beta" from a sidebar link, and I'm going to assume that doesn't affect the prior merge approval.

**Comment by KFishner** [comment]
@nfagerlund @skierkowski thoughts on updating the text on the index page to not reference it being new or rewritten? https://www.terraform.io/docs/enterprise/getting-started/index.html

Maybe something like:

"Terraform Enterprise enables teams to collaborate on Terraform configurations, runs, modules, and states. Check out all the features and functionality [here](https://www.hashicorp.com/products/terraform) and get request a trial"

**Comment by skierkowski** [comment]
Yeah, Agreed. +1 on that copy. I'd also remove the "new" in this intro sentence "Welcome to the ~new~ Terraform Enterprise".

**Comment by nfagerlund** [comment]
@skierkowski @KFishner Yeah, good call. I'll roll that into some other stuff I'm doing in this vicinity soon.

**Pull request merged**
