### PR TITLE
details on AWS load balancers

### PR DESCRIPTION
**Pull request by rberlind**
I added details about using various types of AWS load balancers with PTFE.  This now includes Application, Network, and Classic load balancers.

I also point out that a self-signed cert CAN be used if an Application or Classic LB is used and a public cert is placed on the LB.

I also documented some limitations on using NLBs and AWS Certificate Manager certs.

### CODE REVIEW

**Comment by armchairlinguist** [comment]
I'm not really able to review the technical details here, so I'll leave that to Brian. Feel free to request review again once he's done - I'm always happy to be a copyeditor.

**Comment by roooms** [comment]
Thanks, @rberlind !

As this is a request to change the AWS Reference Architecture, I'd like to give it a review as well.

#437 which is a resubmission (with a fresh merge of master) of an older PR that got missed includes a number of updates to the AWS Reference Architecture.

This PR (#400) should be reviewed for validity against the updated Reference Architecture.

**Comment by rberlind** [comment]
Thanks @roooms.  Glad to see that you have expanded the scope of the deployment options considered. 

I have two main comments:

1) What I was aiming to do in my changes is add more clarity around the various AWS LB options and how to configure them with PTFE.  Your updated version still only mentions Network and Classic Load Balancers in the "Additional AWS Resources" section although you do mention ELBs and ALBs below your first diagram.
2) If using an ALB or a Classic ELB, it seems to make more sense to me to terminate SSL on the load balancer instead of on the PTFE instances since this supports the use of a self-signed certificate on the PTFE instances when using a public cert on the load balancer.  I was trying to get away from the categorical imperative "self-signed certs are bad".  I have seen them used with AWS Certificate Manager Certificates on the load balancers at 2 customers.  Of course, doing SSL termination on the PTFE instances is fine if a public cert is used on them.

I would also add that one customer tried to use a Network Load Balancer and encountered some of the issues that I documented.  I would be fine with removing all references to NLBs and steering customers toward ALBs/ELBs.

**Comment by roooms** [comment]
Thanks for the extra detail @rberlind. I'm not suggesting your changes are not required or valuable, just that I'd like to get the 0.2 release of the RA (#437) published before this one and then review how we incorporate your recommendations (#400) as well. Thanks again for submitting them!

**Comment by rberlind** [comment]
No problem, @roooms.  I had not taken your previous comments as saying anything negative about my proposed changes.  And there is no problem with holding off on my changes.

**Comment by rberlind** [comment]
Hi @blalor and @roooms :  I submitted this doc change more than a month ago.  Any chance you could approve and merge? Unfortunately, because so much time has passed and the doc was revised by others, there now appear to be conflicts.  If you want me to close this PR and do a new one based off the current version of the doc, I could do that.

**Comment by roooms** [comment]
I've merged master into this branch and resolved the conflicts 🎉
Thanks for these updates, @rberlind!

**Pull request merged**
