### PR TITLE
Delete automated-recovery.mdx

### PR DESCRIPTION
**Pull request by jisorondo**
Removing outdated document

### Screenshots

----------

### Merge Checklist
_If items do not apply to your changes, add (N/A) and mark them as complete._

#### Pull Request
- [ ] One or more labels describe the type of change (e.g. clarification) and associated product (e.g. tfc).
- [ ] Description links to related pull requests or issues, if any.

#### Content
- [ ] Redirects have been added for moved, renamed, or deleted pages.
- [ ] Sidebar navigation files have been updated for added, deleted, reordered, or renamed pages.
- [ ] Links to related content where appropriate (e.g., API endpoints, permissions, etc.).
- [ ] Pages with related content are updated and link to this content when appropriate.
- [ ] New pages have metadata (page name and description) at the top.
- [ ] New images are 2048 px wide. They have HashiCorp standard annotation color (#F92672) and format (rectangle with rounded corners), blurred sensitive details (e.g. credentials, usernames, user icons), and descriptive alt text in the markdown for accessibility.
- [ ] New code blocks have the correct syntax and line breaks to eliminate horizontal scroll bars.
- [ ] UI elements (button names, page names, etc.) are bolded.
- [ ] The Vercel website preview successfully deployed.

#### Reviews
- [ ] I or someone else reviewed the content for technical accuracy.
- [ ] I or someone else reviewed the content for typos, punctuation, spelling, and grammar.

### CODE REVIEW

**Comment by jmariedee** [comment]
I can definitely see how this page is problematic- it's not nearly as obvious as it needs to be that snapshots are just a couple settings file backups... but should we not replace the page with something better written instead of outright deleting it?

**Comment by jmariedee** [comment]
This doc page is currently linked to in the [Terraform Enterprise Backup Recommended Pattern](https://learn.hashicorp.com/tutorials/terraform/pattern-backups#database). Need to update that accordingly.

**Comment by jisorondo** [comment]
> This doc page is currently linked to in the [Terraform Enterprise Backup Recommended Pattern](https://learn.hashicorp.com/tutorials/terraform/pattern-backups#database). Need to update that accordingly.

I don't see a link from this page. Which link exactly are you seeing?

**Comment by laurapacilio** [comment]
Hello! Whenever we delete content, we need to add a redirect in the `redirects.js` file so that we don't introduce broken links. 

- Where would we create the redirect to? And when folks get redirected, do we need a note at the top of that page letting folks know that this has been removed/is no longer available?
- Is there an alternative that folks should follow? Apologies, but I don't know much about this change/why this content is no longer relevant but I want to make sure that we give folks an alternative who may be 
- Are we sure that there aren't any customers who could still be using/want to use this content?

**Comment by amy-hashi** [comment]
Closing unmerged. This is something we'll discuss internally and make a decision on.

**Pull request closed without merging**
