### PR TITLE
remove single module comments

### PR DESCRIPTION
**Pull request by rberlind**
PMR modules are no longer restricted to a single module.

## Labels

- [x ] inaccuracy
- [ ] clarification
- [ ] new docs
- [ ] cosmetic bug - fixing broken text or markup
- [ ] enhancement - changing the website's behavior/layout

### CODE REVIEW

**Comment by rberlind** [comment]
Compare the doc I modified to https://www.terraform.io/docs/registry/modules/publish.html#requirements.  But note that while the latter does require a registry description, I just tested that the TFC/E PMR will accept a registry that does not have one when publishing a module to the PMR and that it even creates a description for the module like "Terraform module for s3-bucket on provider aws." based on the name of the module.

The Terraform docs team might want to check whether registry descriptions are really needed in the public registry.  If not, that requirement could be dropped from https://www.terraform.io/docs/registry/modules/publish.html#requirements. But I did not have time to do a test in the public registry.

**Comment by judithpatudith** [comment]
@bethanyr Do you know who can verify this for us? 

@rberlind sorry this sat for so long,  taking a look now. Looks like a link check is failing; do you mind if I rebase if necessary?

**Comment by bethanyr** [comment]
the module description field doesn't appear to be required in the public registry - but I think we want module publishers to include it to provide more information about the module.

**Comment by rberlind** [comment]
@bethanyr : you can handle it anyway you see fit.  Thanks.

**Review by judithpatudith — APPROVED** [review]

**Comment by rberlind** [comment]
I'd prefer you do it, @judithpatudith . Thanks.

**Comment by laurapacilio** [comment]
Merging this - there was one failing link check but a) it's not in anything that was changed here and b) it doesn't appear to actually be broken. So I'm merging anyway.

**Pull request merged**
