### PR TITLE
Update the Enterprise Cluster Architecture

### PR DESCRIPTION
**Pull request by aaron-lane**
## Description

This branch updates the Enterprise > Before Installing > Cluster Architecture documentation to be consistent with the state of the Terraform modules.

### CODE REVIEW

**Comment by aaron-lane** [comment]
I think the [build failure](https://travis-ci.org/github/hashicorp/terraform-website/builds/685809461#L9296-L9299) is unrelated to this branch:

> Found 2 broken links.
http://127.0.0.1:4567/api/
http://127.0.0.1:4567/docs/providers/turbot/r/garnt_activation.html

**Comment by nfagerlund** [comment]
That's correct. One of those has an open PR in the OCI provider, and the other already has a fix merged. 

(If you were to rebase this, you'll see some NEW broken link failures, which also have fixes in flight.)

**Comment by nfagerlund** [comment]
Feel free to merge this at your leisure, or I can merge it if you'd prefer.

**Comment by aaron-lane** [comment]
I converted this back to a draft as there are some more changes required for the internal load balancing description.

**Pull request closed without merging**
