### PR TITLE
Update link preview image for marketing pages

### PR DESCRIPTION
**Pull request by nfagerlund**
- This supersedes https://github.com/hashicorp/terraform-website/pull/553
- Squash before merging. 

In the name of good Slack citizenship, we need to keep preview images small when
users and employees paste docs links into chats, and 95% of the content on this
site is docs. But the marketing pages should use whatever the marketing and design
teams deem brand-appropriate! 

This PR updates the layouts to enable marketing unfurls where needed, and leaves all other pages small-unfurl by default.

So far, we've identified the following pages as marketing content:

- /index.html
- /logos.html
- /intro/* (requires separate PR to terraform repo)

Some interesting stuff I turned up:

- og-image.png needs to stay square, because it's referenced by name as a square image on /logos.html.
- The new, enormously large square og-image.png file is actually a couple kb smaller than the tiny one it replaces. 🤷🏽‍♀️
- /logos.html isn't... actually... linked from anywhere else on terraform.io. How do people get here? Where did it come from?

### CODE REVIEW

**Comment by nfagerlund** [comment]
@mwickett Was Jennifer under a WMFH agreement as a contractor? And is there something I can say to the CLA bot for stuff that was WMFH prior to the CLA going into effect?

**Comment by nfagerlund** [comment]
Oh, I should also mention, I did in fact test all of the affected pages (including the patched /intro/*) in a local build to make sure they were getting the proper large `og:image` etc. tags in their head elements. (I know renaming that one odd `.markdown.html` to `.markdown.html.erb` seems weird, but it works as expected.)

**Comment by mwickett** [comment]
@nfagerlund Jennifer was under contract - I've asked Ashlie Jenkins on our team to help me navigate the legal side of things here. Will update here when I have additional information.

**Comment by nfagerlund** [comment]
Since @phinze and @apparentlymart approved the prior PRs (which used the exact same approach but with a less conservative area of effect), I'm gonna go ahead and merge.

**Pull request merged**
