### PR TITLE
Remove errant single quotes

### PR DESCRIPTION
**Pull request by justinretzolk**
## PR Objective

- [x] Fixing inaccurate docs

## Description

Fairly straightforward! The version of the Automated Recovery sample script that we provide had incorrect single quote, which would lead to a failure to interpolate the variable. This PR removes said single quotes.

### CODE REVIEW

**Comment by nfagerlund** [comment]
Have you confirmed that the old line breaks and the new one works? On what systems?

If so, then 👍🏼

**Comment by justinretzolk** [comment]
I'll defer to @hashitop for his testing of the script itself, as he noticed this when doing some testing/KB writing. I just happened to be around and had enough free time to actually open this PR 😅.

Generally speaking though, the single quotes will stop interpolation, which is why I figured it was safe enough to get this opened without _personally_ testing it:

```
➜ export test="this_is_a_test"
➜ echo '$test'
$test
➜ echo $test
this_is_a_test
```

**Comment by justinretzolk** [comment]
Ah, yes! That lines up with what Top had pointed out - I don't want to speak out of turn here, but I believe the issue was that the single quotes being around the interpolated value still caused an issue. When you're around, mind expanding on what you saw, @hashitop ?

(just to show that you're _completely_ right and I _should_ have done some additional testing on my own!):

```
➜ echo "Is this a test? '$test'"
Is this a test? 'this_is_a_test'
```

**Comment by justinretzolk** [comment]
I was able to do some testing on this and the single quotes do _not_ appear to have any ill effect. Closing this PR.

**Comment by hashitop** [comment]
Yes, it will pass the string with quotes to replicated and the restoration stalled, when open up UI and click browse to try to find snapshot with the string surrounded by the single quotes, the snapshots won't show up.

I can share you the screenshot if that helps

**Comment by hashitop** [comment]
Screen Shot 2020-09-07 at 11 02 55 am

@justinretzolk , I took those few lines from the existing script on the document and ran them with/without the single quotes

**Comment by nfagerlund** [comment]
@hashitop Thanks for the screenshot and the confirmation! If that's what it is, that's what it is. 👍🏼

**Pull request merged**
