### PR TITLE
Fixing a typo within RHEL requirements

### PR DESCRIPTION
**Pull request by sudomateo**
Initial updates to the RHEL requirements docs.

### CODE REVIEW

**Comment by sudomateo** [comment]
You should probably update the Docker pinning section while you're in here.

**Comment by sudomateo** [comment]
Hey please amend your commits instead of pushing new ones.

**Comment by nfagerlund** [comment]
This was a demonstration of some kind, right? Is it still relevant, or should I close?

**Comment by sudomateo** [comment]
@nfagerlund it was supposed to be an update, but this might actually be fixed within the code itself. I'll check tomorrow and close if necessary. Otherwise I'll update the pull request with actual changes. Sorry about that!

**Comment by sudomateo** [comment]
Ready for review!

**Pull request merged**
