### PR TITLE
clarify "working directory" behavior 

### PR DESCRIPTION
**Pull request by mildwonkey**
I'm really struggling with the phrasing here, so I choose to crowdsource this PR - please make suggestions (I will squash commits, I promise)!

### CODE REVIEW

**Comment by nfagerlund** [comment]
I've looked this over and will definitely have some wording suggestions, but I'm waiting on confirmation of how remote CLI plans behave on VCS-backed workspaces with a working directory -- PR #835 is a community PR that's reporting some unexpected behavior around those, and I want to make sure we really understand what's going on there.

**Comment by nfagerlund** [comment]
I did tests. I learned things. Revisions incoming.

**Comment by mildwonkey** [comment]
thank you _so much_ I cannot thank you enough ❤️

**Comment by nfagerlund** [comment]
I went ahead and expanded this to match what I learned! I'm going to go ahead and merge, because I'm getting ready to split out the cloud / enterprise docs, so I'm tying up loose ends -- feel free to open an issue if this needs adjustment!

**Pull request merged**
