### PR TITLE
fixed typo - recomoned to recommend

### PR DESCRIPTION
**Pull request by MrFixit96**
## Labels

- [ ] inaccuracy
- [ ] clarification
- [ ] new docs
- [X] cosmetic bug - fixing broken text or markup
- [ ] enhancement - changing the website's behavior/layout

### CODE REVIEW

**Review by judithpatudith — APPROVED** [review]
Thanks for the fix!

**Review by sudomateo — APPROVED** [review]
Thank you!

**Comment by laurapacilio** [comment]
@MrFixit96 Just reviving this, since it's been a while. Thank you for this fix! As soon as you sign the CLA, we can go ahead and merge.

**Comment by laurapacilio** [comment]
Closing because I believe this will get addressed in this PR (along with a few other issues in this section).  https://github.com/hashicorp/terraform-website/pull/1785

Thank you!

**Pull request closed without merging**
