### PR TITLE
Improve status/response table in api template

### PR DESCRIPTION
**Pull request by nfagerlund**
This is from @dylanegan's improvements in the comments of https://github.com/hashicorp/terraform-website/pull/231.

### CODE REVIEW

**Comment by armchairlinguist** [comment]
This looks great. We will be at the top of the class in API docs! 😸

**Comment by dylanegan** [comment]
@nfagerlund can you update a page here so I can Netlify view it and share it with people for review?

**Comment by nfagerlund** [comment]
@dylanegan sure thing! I went with create a team, since I think that's what your example was from.

**Comment by nfagerlund** [comment]
Hmmm.... yes, we should. 👍🏼

**Pull request merged**
