### PR TITLE
Delete ALL remaining provider submodules and symlinks

### PR DESCRIPTION
**Pull request by nfagerlund**
**Draft status: Still waiting for eight providers to get published/redirected.** 

This change must not be merged to master until all of the remaining providers
have been published and redirected to the registry. 

See also: https://github.com/hashicorp/terraform-website/pull/1604

### CODE REVIEW

**Comment by laurapacilio** [comment]
@nfagerlund I was thinking of closing this out but wanted to ask first :-) Let me know if it's still relevant!

**Comment by nfagerlund** [comment]
That is a great question! Paul Tyng left the company and idk if he rolled these last providers through the migration process yet. I'll go find out.

**Comment by nfagerlund** [comment]
Thing | Registry | Status
-|-|-
Cobbler | https://registry.terraform.io/providers/cobbler/cobbler/latest/docs | Redirected already... but the redirect has a typo!! 😭 "cobber" lmao
Avi | https://registry.terraform.io/providers/vmware/avi/latest/docs | Needs redirect
Rundeck | https://registry.terraform.io/providers/rundeck/rundeck/latest | Needs redirect.
Infoblox | https://registry.terraform.io/providers/infobloxopen/infoblox/latest/docs | Needs redirect.
Chef | https://registry.terraform.io/providers/terrycain/chef/latest/docs | Can't tell if this is just some rando, or if they've taken it over in an official-enough way.
Genymotion | x | Nuthin'.
Mysql | x | Looks like there's five unofficial forks of it. 😑
Rubrik | x | Nuthin'.

Okay, so there's four of them we can slam the door on, but that still leaves us with four zombies, and I'm not sure what to tell you to do about it. I'll do a quick bit of research to see if I can deal with the first four, and... I guess hit me back later if I don't come up with something to do about the last four.

**Comment by nfagerlund** [comment]
@laurapacilio I did the thing! This PR is now safe to merge.

**Comment by laurapacilio** [comment]
YAY! thank you!!

**Pull request merged**
