### PR TITLE
Make code blocks visually obvious

### PR DESCRIPTION
**Pull request by ovidiub13**
Restoring the aspect of code blocks for code in paragraphs, so they are visually more evident than the regular text.

### CODE REVIEW

**Comment by ovidiub13** [comment]
Before:
----

screen shot 2018-08-08 at 17 47 23

After:
----

screen shot 2018-08-08 at 17 47 07

**Comment by nfagerlund** [comment]
Thanks for this, and apologies for letting it languish for some months; I think it showed up when there was some uncertainty about what was happening with the web design in the near term, but at this point I'm pretty sure this won't interfere with future plans in the slightest.

**Comment by nfagerlund** [comment]
@ovidiub13 Could I please get you to sign the HashiCorp CLA? After that, I'll rebase and merge this.

**Comment by ovidiub13** [comment]
Hello @nfagerlund . Thank you for the feedback. I've signed the CLA.

**Comment by nfagerlund** [comment]
@ovidiub13 excellent, thank you!

**Pull request merged**
